services:
  nodepanel:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nodepanel

    restart: unless-stopped

    ports:
      - "4000:4000"

    environment:
      NODE_ENV: production
      PORT: "4000"
