- name: Build do projeto
  run: |
    npm install
    npm run build -w client

- name: Debug build
  run: |
    ls -la
    ls -la client/dist

- name: Enviar arquivos via SCP
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    key: ${{ secrets.SSH_KEY }}
    source: "client/dist/*"
    target: "/home/dev-console-wrodrigues/htdocs/console.wrodrigues.dev.br"
